# Generated by Django 5.1 on 2024-12-08 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_name_alter_board_order_alter_column_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(error_messages={'blank': 'El nombre no puede estar vacío.'}, max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='El nombre no puede exceder 100 caracteres.')]),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('name', 'board'), name='unique_column_name_per_board'),
        ),
    ]
