# Generated by Django 5.1 on 2024-12-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_board_name_alter_board_order_alter_column_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='column',
            name='unique_column_name_per_board',
        ),
    ]
