# Generated by Django 5.1 on 2024-12-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_remove_column_unique_column_name_per_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
